server:
  port: 8888
spring:
  application:
    name: spring-boot-quartz-manage
eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://10.3.98.153:1111/eureka/  #注册中心地址
druid:
  jdbc:
    driveClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/db_quartz
    jdbcUsername: root
    jdbcPassword: sunwei
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 3
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBrowwon: false
    testOnReturn: false
    filters: stat,wall
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.huntkey.rx.springbootquartzmanage.entity
debug: true